### ISSUE TITLE
Test error: Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ponferrada#133]
We currently have those errors when executing DOM tests in package `sanes-chrome-extension`:

```
PASS src/routes/welcome/index.dom.spec.ts (8.829s)
  ● Console

    console.error ../../node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
          at module.exports (/some/place/ponferrada/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at HTMLCanvasElementImpl.getContext (/some/place/ponferrada/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
          at HTMLCanvasElement.getContext (/some/place/ponferrada/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
          at /some/place/ponferrada/node_modules/jspdf/dist/jspdf.min.js:270:5484
          at /some/place/ponferrada/node_modules/jspdf/dist/jspdf.min.js:270:7062
          at /some/place/ponferrada/node_modules/jspdf/dist/jspdf.min.js:1:89
          at Object.<anonymous> (/some/place/ponferrada/node_modules/jspdf/dist/jspdf.min.js:1:93)
          at Runtime._execModule (/some/place/ponferrada/node_modules/jest-runtime/build/index.js:858:13)
          at Runtime._loadModule (/some/place/ponferrada/node_modules/jest-runtime/build/index.js:551:12)
          at Runtime.requireModule (/some/place/ponferrada/node_modules/jest-runtime/build/index.js:415:10) undefined
```

There are discussions in
* [jest-canvas-mock](https://github.com/hustcc/jest-canvas-mock/issues/2)
* [jsom](https://github.com/jsdom/jsdom/pull/1964)

So this issue is probably fixed in jsdom 13.0.0+.

Unfortunately, our `jest-environment-jsdom` uses an old version of `jsdom`

```
jest-environment-jsdom@^24.7.1:
  version "24.7.1"
  resolved "https://registry.yarnpkg.com/jest-environment-jsdom/-/jest-environment-jsdom-24.7.1.tgz#a40e004b4458ebeb8a98082df135fd501b9fbbd6"
  integrity sha512-Gnhb+RqE2JuQGb3kJsLF8vfqjt3PHKSstq4Xc8ic+ax7QKo4Z0RWGucU3YV+DwKR3T9SYc+3YCUQEJs8r7+Jxg==
  dependencies:
    "@jest/environment" "^24.7.1"
    "@jest/fake-timers" "^24.7.1"
    "@jest/types" "^24.7.0"
    jest-mock "^24.7.0"
    jest-util "^24.7.1"
    jsdom "^11.5.1"
```

Since jest-canvas-mock is not used in our project, I think the issue is the old jsdom.

**Comment by webmaster128** [comment]
We cannot easily [setup](https://github.com/hustcc/jest-canvas-mock#setup) `jest-canvas-mock` because of

```
Out of the box, Create React App only supports overriding these Jest options:

  • collectCoverageFrom
  • coverageReporters
  • coverageThreshold
  • extraGlobals
  • globalSetup
  • globalTeardown
  • resetMocks
  • resetModules
  • snapshotSerializers
  • watchPathIgnorePatterns.

These options in your package.json Jest configuration are not currently supported by Create React App:

  • setupFiles

If you wish to override other Jest options, you need to eject from the default setup. You can do so by running npm run eject but remember that this is a one-way operation. You may also file an issue with Create React App to discuss supporting more options out of the box.
```

**Comment by alexlouden** [comment]
I switched to using https://github.com/ianschmitz/jest-environment-jsdom-fourteen instead, which uses jsdom v14 and fixes the issue detecting `canvas`.

```bash
yarn add --dev jest-environment-jsdom-fourteen canvas
yarn test --env=jest-environment-jsdom-fourteen
```

Hope this helps! :)

**Comment by eMarek** [comment]
I had the same issue using Create React App and `jsPDF` in tests and I have finally fixed it.

My current environment is:
`node: v12.16.1, npm: 6.13.4, yarn: 1.22.4, react-scripts: 3.4.1, jspdf: 1.5.3`.

You can force certain package to be dependant by exact package version and you can do it with `resolutions` in package.json (if you are using Yarn). In our case `jsdom` is the issue so here the resolution:
```
  "resolutions": {
    "**/jest-environment-jsdom/jsdom": "13.0.0"
  }
```
Since `canvas` support was dropped in this exact version, you also have to add it as dev dependency in package.json:
```
  "devDependencies": {
    ...
    "canvas": "^2.6.1",
    ...
  }
```
Let me know if it works for you as well.
